<div ng-controller="wxCtrl">
	<a target="_blank" ng-href="{{ authModel.url }}/<?php echo $this->websiteId?>" class="btn btn-primary">authorised</a>
</div>

<script>
	var adminApp = angular.module('adminApp',[]);
	adminApp.controller('wxCtrl', ['$scope', '$http', function($scope, $http){
		$scope.authModel = {};
		$http.get('/redirecturi').success(function(data){
			console.log(data);
			$scope.authModel.url = data.redirectUri;
		});		
	}]);
</script>