<div ng-controller="wxCtrl">
	<a ng-href="https://mp.weixin.qq.com/cgi-bin/componentloginpage?component_appid=wx2ce4babba45b702d&pre_auth_code={{authModel.preAuthCode}}&redirect_uri=http://wx.fucmsweb.com/callback" class="btn btn-primary">authorised</a>
</div>
<script>
	var adminApp = angular.module('adminApp',[]);
	adminApp.controller('wxCtrl', ['$scope', '$http', function($scope, $http){
		$scope.authModel = {};
		$http.post('https://api.weixin.qq.com/cgi-bin/component/api_create_preauthcode?component_access_token=wx2ce4babba45b702d').success(function(data){
			console.log(data.pre_auth_code);
			$scope.authModel.preAuthCode = data.pre_auth_code;
		});		
	}]);
</script>