<div ng-controller="wxCtrl">
	<a target="_blank" ng-href="{{ authModel.url }}/test" class="btn btn-primary">微信公众号授权</a>
</div>

<script>
	var adminApp = angular.module('adminApp',[]);
	adminApp.controller('wxCtrl', ['$scope', '$http', function($scope, $http){
		$scope.authModel = {};
		$http.get('/redirecturi').success(function(data){
			$scope.authModel.url = data.redirectUri;
		});
	}]);
</script>