<?php echo $this->doctype(); ?>

<html ng-app='adminApp'>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<meta name="renderer" content="webkit" />
	<meta name="format-detection" content="telephone=no" />
	<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1" />
	
	<link href="<?php echo $this->path('src')?>/bootstrap/3.3.1/bootstrap.min.css" rel="stylesheet" type="text/css" />
	
	<script src='<?php echo $this->path('compact')?>/account/~app/_.js' type='text/javascript'></script>
	<script>
		var appRequiredModules = [];
	</script>
</head>
<body>
<div class='page-container'>
	
	<div id='content' class='content'>
		<?php echo $this->content; ?>
	</div>
</div>
</body>
</html>