<?php

namespace DoctrineMongoHydrator;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\UnitOfWork;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class ApplicationDocumentAdminHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate($document, $data, array $hints = array())
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id'])) {
            $value = $data['_id'];
            $return = $value instanceof \MongoId ? (string) $value : $value;
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['appId'])) {
            $value = $data['appId'];
            $return = (string) $value;
            $this->class->reflFields['appId']->setValue($document, $return);
            $hydratedData['appId'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['appSecret'])) {
            $value = $data['appSecret'];
            $return = (string) $value;
            $this->class->reflFields['appSecret']->setValue($document, $return);
            $hydratedData['appSecret'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['ticket'])) {
            $value = $data['ticket'];
            $return = (string) $value;
            $this->class->reflFields['ticket']->setValue($document, $return);
            $hydratedData['ticket'] = $return;
        }

        /** @Field(type="hash") */
        if (isset($data['data'])) {
            $value = $data['data'];
            $return = $value;
            $this->class->reflFields['data']->setValue($document, $return);
            $hydratedData['data'] = $return;
        }
        return $hydratedData;
    }
}